apiVersion: v1
kind: Service
metadata:
  name: vidarbha-rainfall-api
  labels:
    app: vidarbha-rainfall-api
spec:
  type: ClusterIP
  selector:
    app: vidarbha-rainfall-api
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
